apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: yelb-appserver
  namespace: yelb
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yelb-appserver
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
#  behavior:
#    scaleDown:
#      stabilizationWindowSeconds: 120
#      policies:
#      - type: Percent
#        value: 20
#        periodSeconds: 30
#      - type: Pods
#        value: 2
#        periodSeconds: 30
#      selectPolicy: Min
#    scaleUp:
#      stabilizationWindowSeconds: 0
#      policies:
#      - type: Percent
#        value: 100
#        periodSeconds: 15
#      - type: Pods
#        value: 4
#        periodSeconds: 15
#      selectPolicy: Max
#
