apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: yelb-appserver
  namespace: yelb
spec:
  maxReplicas: 2
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yelb-appserver
  targetCPUUtilizationPercentage: 50

